export const pokemonData = [
  {
    id: 1,
    name: "Bulbasaur",
    types: ["Grass", "Poison"],
    abilities: ["Overgrow", "Chlorophyll"],
    hp: 45,
    attack: 49,
    defense: 49,
    spAttack: 65,
    spDefense: 65,
    speed: 45,
    height: 0.7,
    weight: 6.9,
    description: "A calm starter that can absorb sunlight to power up over time.",
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png"
  },
  {
    id: 4,
    name: "Charmander",
    types: ["Fire"],
    abilities: ["Blaze", "Solar Power"],
    hp: 39,
    attack: 52,
    defense: 43,
    spAttack: 60,
    spDefense: 50,
    speed: 65,
    height: 0.6,
    weight: 8.5,
    description: "Its tail flame shows how healthy and energetic it feels.",
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png"
  },
  {
    id: 7,
    name: "Squirtle",
    types: ["Water"],
    abilities: ["Torrent", "Rain Dish"],
    hp: 44,
    attack: 48,
    defense: 65,
    spAttack: 50,
    spDefense: 64,
    speed: 43,
    height: 0.5,
    weight: 9,
    description: "Its shell protects it from attacks and helps it swim quickly.",
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png"
  },
  {
    id: 25,
    name: "Pikachu",
    types: ["Electric"],
    abilities: ["Static", "Lightning Rod"],
    hp: 35,
    attack: 55,
    defense: 40,
    spAttack: 50,
    spDefense: 50,
    speed: 90,
    height: 0.4,
    weight: 6,
    description: "Stores electricity in cheek pouches and releases strong shocks.",
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png"
  },
  {
    id: 94,
    name: "Gengar",
    types: ["Ghost", "Poison"],
    abilities: ["Cursed Body"],
    hp: 60,
    attack: 65,
    defense: 60,
    spAttack: 130,
    spDefense: 75,
    speed: 110,
    height: 1.5,
    weight: 40.5,
    description: "Lurks in shadows and can vanish into darkness instantly.",
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png"
  },
  {
    id: 130,
    name: "Gyarados",
    types: ["Water", "Flying"],
    abilities: ["Intimidate", "Moxie"],
    hp: 95,
    attack: 125,
    defense: 79,
    spAttack: 60,
    spDefense: 100,
    speed: 81,
    height: 6.5,
    weight: 235,
    description: "Its violent nature appears when it evolves from Magikarp.",
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png"
  },
  {
    id: 143,
    name: "Snorlax",
    types: ["Normal"],
    abilities: ["Immunity", "Thick Fat", "Gluttony"],
    hp: 160,
    attack: 110,
    defense: 65,
    spAttack: 65,
    spDefense: 110,
    speed: 30,
    height: 2.1,
    weight: 460,
    description: "Sleeps for most of the day and wakes mostly to eat.",
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png"
  },
  {
    id: 149,
    name: "Dragonite",
    types: ["Dragon", "Flying"],
    abilities: ["Inner Focus", "Multiscale"],
    hp: 91,
    attack: 134,
    defense: 95,
    spAttack: 100,
    spDefense: 100,
    speed: 80,
    height: 2.2,
    weight: 210,
    description: "A kind-hearted dragon known for rescuing ships in storms.",
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png"
  },
  {
    id: 448,
    name: "Lucario",
    types: ["Fighting", "Steel"],
    abilities: ["Steadfast", "Inner Focus", "Justified"],
    hp: 70,
    attack: 110,
    defense: 70,
    spAttack: 115,
    spDefense: 70,
    speed: 90,
    height: 1.2,
    weight: 54,
    description: "Can sense aura and read opponents before they strike.",
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/448.png"
  },
  {
    id: 700,
    name: "Sylveon",
    types: ["Fairy"],
    abilities: ["Cute Charm", "Pixilate"],
    hp: 95,
    attack: 65,
    defense: 65,
    spAttack: 110,
    spDefense: 130,
    speed: 60,
    height: 1,
    weight: 23.5,
    description: "Its ribbon-like feelers soothe allies and calm conflicts.",
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/700.png"
  },
  {
    id: 778,
    name: "Mimikyu",
    types: ["Ghost", "Fairy"],
    abilities: ["Disguise"],
    hp: 55,
    attack: 90,
    defense: 80,
    spAttack: 50,
    spDefense: 105,
    speed: 96,
    height: 0.2,
    weight: 0.7,
    description: "Hides under a homemade disguise to look less frightening.",
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/778.png"
  },
  {
    id: 912,
    name: "Quaxly",
    types: ["Water"],
    abilities: ["Torrent", "Moxie"],
    hp: 55,
    attack: 65,
    defense: 45,
    spAttack: 50,
    spDefense: 45,
    speed: 50,
    height: 0.5,
    weight: 6.1,
    description: "A tidy duck Pokemon known for its glossy, styled feathers.",
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/912.png"
  }
];
